DISCARD_CARDS_EFFECT            = 1
DRAW_CARDS_EFFECT               = 2
GAIN_RUNES_EFFECT               = 3
GAIN_HONOR_EFFECT               = 4
GAIN_POWER_EFFECT               = 5
BANISH_CARD_IN_HAND_EFFECT      = 6
BANISH_CARD_IN_CENTER_EFFECT    = 7
BANISH_CARD_FROM_DICARD_EFFECT  = 8








DRAW_CARD_TWO_CONSTRUCTS_EFFECT = 17
